const MIN_ID_NUMBER = 1;
const MAX_ID_NUMBER = 25;
const MAX_AVATAR_NUMBER = 6;
const MIN_LIKE_NUMBER = 15;
const MAX_LIKE_NUMBER = 200;
const MAX_COMMENT_NUMBER = 1000;
const MAX_ARRAY_LENGHT = 25;
export {MIN_ID_NUMBER,MAX_ID_NUMBER, MAX_AVATAR_NUMBER, MIN_LIKE_NUMBER,MAX_LIKE_NUMBER,MAX_COMMENT_NUMBER,MAX_ARRAY_LENGHT };
